In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv('statistics.csv',index_col=0)

In [3]:
stats=stats.drop(['dof','chi2','oddsratio'])

In [4]:
data = stats.reset_index()

In [5]:
x=stats.stack().reset_index()

In [6]:
x.columns=['test','symbol','value']

In [7]:
y=x.sort_values(['test','value'],ascending=False)

In [8]:
y=y.reset_index(drop=True)

In [9]:
group = y.groupby('test')

In [10]:
group_name  = list(group.groups.keys())

In [11]:
list_test = []

In [12]:
for name in group_name:
    res = group.get_group(name).pivot(index='symbol',columns='test',values='value')\
    .sort_values(by = name).reset_index()
    list_test.append(res)

In [13]:
result = pd.concat(list_test,axis=1)

In [14]:
result

test,symbol,accuracy_score,symbol,adjusted_rand_score,symbol,matthews_corrcoef,symbol,mutual_info_score,symbol,p,symbol,p_value
0,"('PGSUS', 'TSKB')",0.003001,"('TSKB', 'KCHOL')",-0.002335,"('EKGYO', 'KCHOL')",-0.040325,"('KOZAL', 'TSKB')",6.167299e-07,"('KOZAA', 'KOZAL')",0.000000e+00,"('KOZAA', 'KOZAL')",0.000000e+00
1,"('KOZAL', 'TSKB')",0.003320,"('TSKB', 'ASELS')",-0.001795,"('EKGYO', 'BIMAS')",-0.035789,"('DOHOL', 'FROTO')",2.157690e-06,"('KOZAL', 'KOZAA')",0.000000e+00,"('KOZAL', 'KOZAA')",0.000000e+00
2,"('KOZAA', 'TSKB')",0.003482,"('TSKB', 'AKBNK')",-0.001567,"('TSKB', 'BIMAS')",-0.034531,"('BIMAS', 'EKGYO')",2.254139e-06,"('THYAO', 'GARAN')",2.293114e-218,"('THYAO', 'GARAN')",1.070312e-224
3,"('TKFEN', 'TSKB')",0.003836,"('TSKB', 'FROTO')",-0.001494,"('TSKB', 'FROTO')",-0.027449,"('KOZAA', 'TSKB')",9.452668e-06,"('THYAO', 'PGSUS')",2.758278e-205,"('THYAO', 'PGSUS')",1.516316e-209
4,"('THYAO', 'TSKB')",0.003906,"('DOHOL', 'FROTO')",-0.000881,"('TSKB', 'EREGL')",-0.014043,"('SAHOL', 'TSKB')",1.102698e-05,"('GARAN', 'AKBNK')",5.683769e-202,"('GARAN', 'AKBNK')",1.788275e-207
...,...,...,...,...,...,...,...,...,...,...,...,...
865,"('TSKB', 'GARAN')",0.332677,"('AKBNK', 'GARAN')",0.013370,"('AKBNK', 'GARAN')",0.118423,"('ISCTR', 'AKBNK')",2.195165e-02,"('DOHOL', 'BIMAS')",8.322343e-01,"('DOHOL', 'BIMAS')",1.000000e+00
866,"('TSKB', 'TCELL')",0.335306,"('KRDMD', 'EREGL')",0.015783,"('ISCTR', 'VAKBN')",0.118678,"('ISCTR', 'VAKBN')",2.246204e-02,"('BIMAS', 'EKGYO')",9.157813e-01,"('DOHOL', 'FROTO')",1.000000e+00
867,"('TSKB', 'TOASO')",0.340594,"('VAKBN', 'GARAN')",0.016580,"('VAKBN', 'GARAN')",0.124293,"('VAKBN', 'GARAN')",2.312548e-02,"('TSKB', 'KCHOL')",9.191167e-01,"('KOZAL', 'TSKB')",1.000000e+00
868,"('TSKB', 'TKFEN')",0.363992,"('HALKB', 'GARAN')",0.016803,"('HALKB', 'GARAN')",0.129235,"('HALKB', 'GARAN')",2.555625e-02,"('KOZAL', 'TSKB')",9.685550e-01,"('TSKB', 'KOZAL')",1.000000e+00
869,"('TSKB', 'PGSUS')",0.381423,"('ISCTR', 'GARAN')",0.019146,"('ISCTR', 'GARAN')",0.134723,"('ISCTR', 'GARAN')",2.738163e-02,"('DOHOL', 'FROTO')",9.969601e-01,"('SAHOL', 'TSKB')",1.000000e+00

In [18]:
result.to_excel('test_result.xlsx',index=False)